# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Endor Labs
on:
  push:
    branches: [ "endorlabs-scan" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '22 14 * * 6'
jobs:
  scan:
    permissions:
      security-events: write # Used to upload sarif artifact to GitHub
      contents: read # Used to checkout a private repository by actions/checkout.
      actions: read # Required for private repositories to upload sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication to Endor Labs
    runs-on: ubuntu-latest
    env:
      ENDOR_NAMESPACE: darren-demo.ospo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: pip install
      run: |
        python3 -m venv .venv
        .venv/bin/pip3 install .
        
    - name: Endor Labs scan pull request
      if: github.event_name == 'pull_request'
      uses: endorlabs/github-action@b51bd06466b545f01a6ac788e3e1147695d3936c
      with:
        namespace: ${{ env.EDNOR_NAMESPACE }}
    - name: Endor Labs scan monitor
      if: github.event_name == 'push'
      uses: endorlabs/github-action@b51bd06466b545f01a6ac788e3e1147695d3936c
      with:
        namespace: ${{ env.EDNOR_NAMESPACE }}
        ci_run: "false"

